/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jhxd_serial_serialService */

#ifndef _Included_com_jhxd_serial_serialService
#define _Included_com_jhxd_serial_serialService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jhxd_serial_serialService
 * Method:    serialOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jhxd_serial_serialService_serialOpen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jhxd_serial_serialService
 * Method:    serialPortSetting
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_jhxd_serial_serialService_serialPortSetting
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_jhxd_serial_serialService
 * Method:    serialRead
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_jhxd_serial_serialService_serialRead
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     com_jhxd_serial_serialService
 * Method:    serialWrite
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_jhxd_serial_serialService_serialWrite
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     com_jhxd_serial_serialService
 * Method:    serialClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jhxd_serial_serialService_serialClose
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
