
#ifndef RK_PIN_ARRAY_CTRL_H
#define RK_PIN_ARRAY_CTRL_H

enum {
	/* Output */
	RK_PAC_PIN_3G_PWR = 0,
	RK_PAC_PIN_3G_RST,
	RK_PAC_PIN_SIM_SWITCH,
	RK_PAC_PIN_USB_HOST_1_2,
	RK_PAC_PIN_USB_HOST_3,
	RK_PAC_PIN_OUTPUT_1,
	RK_PAC_PIN_OUTPUT_2,
	RK_PAC_PIN_HDMI_IN,
	RK_PAC_PIN_LED_EN,
	/* Input */
	RK_PAC_PIN_CHARGER,
	RK_PAC_PIN_DC,
	RK_PAC_PIN_INPUT_1,
	RK_PAC_PIN_INPUT_2,
	RK_PAC_PIN_INPUT_3,
	RK_PAC_PIN_ACC,
	RK_PAC_PIN_MAX,
};

#define MY_MACIG 'G'
#define READ_IOCTL _IOR(MY_MACIG, 0, int)
#define WRITE_IOCTL _IOW(MY_MACIG, 1, int)

#define RK_PAC_IOCTL_CMD_SET_ENABLE  _IOR(MY_MACIG, 0, int)
#define RK_PAC_IOCTL_CMD_SET_DISABLE _IOW(MY_MACIG, 1, int)
#define RK_PAC_IOCTL_CMD_READ        _IOW(MY_MACIG, 2, int)

#if 0
#define RK_PAC_IOCTL_CMD_SET_ENABLE  (0)
#define RK_PAC_IOCTL_CMD_SET_DISABLE (1)
#define RK_PAC_IOCTL_CMD_READ        (2)
#endif

#endif /* End RK_PIN_ARRAY_CTRL_H */
